apiVersion: v1
kind: Namespace
metadata:
  name: k8s-acl-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: k8s-acl-operator
    app.kubernetes.io/part-of: k8s-acl-operator
    app.kubernetes.io/managed-by: kustomize
