---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-acl-operator-controller-manager
  namespace: k8s-acl-operator-system
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-acl-operator
    app.kubernetes.io/part-of: k8s-acl-operator
    app.kubernetes.io/managed-by: kustomize

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-acl-operator-manager-role
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: manager-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-acl-operator
    app.kubernetes.io/part-of: k8s-acl-operator
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.operator.io
  resources:
  - namespacerbacconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.operator.io
  resources:
  - namespacerbacconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.operator.io
  resources:
  - namespacerbacconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-acl-operator-manager-rolebinding
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-acl-operator
    app.kubernetes.io/part-of: k8s-acl-operator
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-acl-operator-manager-role
subjects:
- kind: ServiceAccount
  name: k8s-acl-operator-controller-manager
  namespace: k8s-acl-operator-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-acl-operator-metrics-reader
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-acl-operator
    app.kubernetes.io/part-of: k8s-acl-operator
    app.kubernetes.io/managed-by: kustomize
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-acl-operator-proxy-role
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxy-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-acl-operator
    app.kubernetes.io/part-of: k8s-acl-operator
    app.kubernetes.io/managed-by: kustomize
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-acl-operator-proxy-rolebinding
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-acl-operator
    app.kubernetes.io/part-of: k8s-acl-operator
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-acl-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: k8s-acl-operator-controller-manager
  namespace: k8s-acl-operator-system
