apiVersion: v1
kind: Service
metadata:
  name: k8s-acl-operator-controller-manager-metrics-service
  namespace: k8s-acl-operator-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: k8s-acl-operator
    app.kubernetes.io/part-of: k8s-acl-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
