{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "k8s-acl-operator.namespace" . }}
  labels:
    control-plane: controller-manager
    {{- include "k8s-acl-operator.labels" . | nindent 4 }}
{{- end }}
