apiVersion: v2
name: k8s-acl-operator
description: A Kubernetes operator for automatic RBAC management based on namespace lifecycle
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/yourusername/k8s-acl-operator
sources:
  - https://github.com/yourusername/k8s-acl-operator
keywords:
  - kubernetes
  - rbac
  - operator
  - security
maintainers:
  - name: Your Name
    email: your.email@example.com